### ISSUE TITLE
Run on Charades 

### ISSUE THREAD

**Issue by LIUQI-creat** [klauscc/TALLFormer#6]
Hello, the author, thanks for your excellent work！I want to run your code on the Charades dataset(https://prior.allenai.org/projects/charades). How to write the code to make the code run on the Charades? Thank you very much!

**Comment by LIUQI-creat** [comment]
@klauscc

**Comment by klauscc** [comment]
Thanks for your interest. I didn't run experiments on Charades. I'd suggest you to use other codebase that already implement the training and inference on Charades. Our core part is the memory-saving backbone and it can be inserted to any action detector. You can check here to see how to do it:
https://github.com/klauscc/TALLFormer/blob/main/AFSD/anet_video_cls/membank/model.py
https://github.com/klauscc/TALLFormer/blob/main/vedatad/models/backbones/chunk_model.py

**Comment by SimoLoca** [comment]
Hi @klauscc, first of all congratulations on the work you've done, I'm sorry to bother you, but I would like to ask some questions about the memory-saving mechanism you've mentioned because I am interested to try it in other codebase.

If I'm not mistaken, the **ChunkVideoSwin** (in https://github.com/klauscc/TALLFormer/blob/main/vedatad/models/backbones/chunk_model.py) and the **BDNetMemBank** (in https://github.com/klauscc/TALLFormer/blob/main/AFSD/anet_video_cls/membank/model.py) are essentially the same thing that manage the memory-bank, but in different ways for Thumos and ActivityNet, respectively.

Thus, for Thumos you employ the **MemBankTrainEngine** (https://github.com/klauscc/TALLFormer/blob/main/vedatad/engines/train_engine.py) that will update the memory-bank thanks to the **MemSingleStageDetector** detector (https://github.com/klauscc/TALLFormer/blob/main/vedatad/models/detectors/mem_single_stage_detector.py).
While for ANet it is managed inside the **BDNetMemBank**.

So my question is: do you have mentioned both ChunkVideoSwin and BDNetMemBank because they are complementary (and so I do not understand correctly how does they work) or maybe because it's up to us which one tho choose in a given context?
And if I'm wrong, could you kindly shed some light on the errors made?

Thanks you so much!

**Comment by klauscc** [comment]
Hi @SimoLoca, 
Yes. **ChunkVideoSwin** and **BDNetMemBank** are complementary. 
**ChunkVideoSwin** is just a wrapper to the original `VideoSwin` to make it able to receive `chunk first` input.  **BDNetMemBank** will divide the inputs into chunks, and then feed some chunks to the **ChunkVideoSwin** to extract features for those chunks.

**Comment by SimoLoca** [comment]
Thanks a lot for the reply.
But for Thumos training/test you did not employ **BDNetMemBank**, right?
Forgive me for my confusion.

**Comment by klauscc** [comment]
Yes, for THUMOS we use **MemSingleStageDetector**, which is equivalent to the **BDNetMemBank** for ActivityNet.

Also **MemBankTrainEngine** (for THUMOS) is equivalent to [membank_dataset.py](https://github.com/klauscc/TALLFormer/blob/main/AFSD/anet_video_cls/membank/membank_dataset.py#L93) (load features from membank) and [model.py](https://github.com/klauscc/TALLFormer/blob/main/AFSD/anet_video_cls/membank/model.py#L90) (update membank).

The logic is like this: 1) split input frames into two group; 2) select features of first group from the memory bank; 3) extract features of the second group using the backbone; 4) update the membank using 3)'s features; 5) concat the features and feed to the following layers. Later when I got sometime I may write a general module for these 5 steps that makes it easier to be adapted to different codebases.

**Comment by SimoLoca** [comment]
Thank you very much for your answer, I couldn't have asked for a better explanation.
All my doubts have been resolved.
Thank you again and I wish you many good things.
